In [33]:
import singstatdata as st
import requests
import json
import re
import pandas as pd
from requests.exceptions import HTTPError
from IPython.display import display

### Creating a timeseries_search() object
> In order to search through Singstat time series datasets for datasets related to property and prices, I will instantiate a timeseries_search() object with the relevant keyphrases.

In [34]:
data = st.timeseries_search(keyphrases=['house','price'],match_all=True)

> Note that if there are no datasets which match the arguments input in the instantiation of the timeseries_search object, an error will be raised as follows:

In [35]:
no_data = st.timeseries_search(keyphrases=['house','food'],match_all=True)

ValueError: No relevant datasets for given keyphrase

#### Accessing information about datasets through timeseries_search() object's attributes

In [36]:
data.resource_ids

[17091, 17092, 17090, 17089]

>The overview attriute of timeseries_search() presents metadata of the returned timeseries datasets in a pandas DataFrame

In [37]:
data.overview

,resourceId,title,frequency,uom,datasource,footnote,startPeriod,endPeriod,variables
0,17089,Percent Change In Consumer Price Index (CPI) B...,Half-Yearly,Per Cent,SINGAPORE DEPARTMENT OF STATISTICS,"""The weighting pattern for the 2019-based CPI ...",1994 H1,2020 H1,"[{'variableCode': 'M213001.2.4', 'variableName..."
1,17090,Consumer Price Index (CPI) By Household Income...,Half-Yearly,Index,SINGAPORE DEPARTMENT OF STATISTICS,"""The weighting pattern for the 2019-based CPI ...",1993 H1,2020 H1,"[{'variableCode': 'M212991.4.11', 'variableNam..."
2,17091,Percent Change In Consumer Price Index (CPI) B...,Annual,Per Cent,SINGAPORE DEPARTMENT OF STATISTICS,"""The weighting pattern for the 2019-based CPI ...",1994,2019,"[{'variableCode': 'M213021.4.1.2', 'variableNa..."
3,17092,Consumer Price Index (CPI) By Household Income...,Annual,Index,SINGAPORE DEPARTMENT OF STATISTICS,"""The weighting pattern for the 2019-based CPI ...",1993,2019,"[{'variableCode': 'M213011.2.1.2', 'variableNa..."

>The full timeseries data is stored in a dictionary under the timeseries attriute of timeseries_search(). The timeseries attribute can thus be indexed by the resourceId of the dataset of interest. The data is then returned in a pandas DataFrame.

In [38]:
data.timeseries[17092]

variableCode,M213011.2.1.2,M213011.4.2,M213011.2.6,M213011.4.9,M213011.2.8,M213011.3.1,M213011.3.1.1,M213011.2.5,M213011.4.6,M213011.2.2,...,M213011.4.10,M213011.2.7,M213011.4.8,M213011.2.1.1,M213011.4.3,M213011.3.8,M213011.2.1,M213011.4.11,M213011.2.11,M213011.3.11
variableName,Food Servicing Services,Clothing & Footwear,Transport,Education,Recreation & Culture,Food,Food Excl Food Servicing Services,Health Care,Transport,Clothing & Footwear,...,Miscellaneous Goods & Services,Communication,Recreation & Culture,Food Excl Food Servicing Services,Housing & Utilities,Recreation & Culture,Food,All Items Less Imputed Rentals On Owner-occupied Accommodation,All Items Less Imputed Rentals On Owner-occupied Accommodation,All Items Less Imputed Rentals On Owner-occupied Accommodation
time,,,,,,,,,,,,,,,,,,,,,
1993,62.064,89.479,65.318,40.333,95.882,60.885,59.462,54.528,79.688,89.488,...,76.312,109.068,85.198,59.170,76.269,88.147,60.645,NaN,NaN,NaN
1994,64.599,91.880,66.440,41.456,98.553,63.040,61.333,56.125,93.395,91.384,...,77.904,110.124,85.731,61.000,78.115,89.414,62.809,NaN,NaN,NaN
1995,66.468,93.348,67.606,42.986,101.623,64.474,62.273,56.881,92.770,92.464,...,78.541,109.801,86.015,61.945,79.132,90.412,64.190,NaN,NaN,NaN
1996,68.240,93.564,68.788,45.243,103.177,65.864,63.321,58.141,91.915,92.932,...,79.004,109.394,86.887,63.062,80.114,91.494,65.615,NaN,NaN,NaN
1997,69.272,94.405,71.673,46.761,102.488,67.211,64.879,60.297,98.410,93.820,...,79.411,108.440,85.935,64.688,84.110,90.575,66.966,NaN,NaN,NaN
1998,70.044,93.018,73.633,49.371,99.618,67.352,64.218,63.067,84.435,93.218,...,80.067,107.401,82.200,63.981,86.583,87.404,66.954,NaN,NaN,NaN
1999,70.427,91.108,73.107,51.252,98.311,67.919,65.015,63.340,86.298,91.418,...,80.883,106.148,81.643,64.770,83.209,86.613,67.550,NaN,NaN,NaN
2000,70.836,90.833,75.802,52.732,98.533,68.260,65.333,64.041,87.158,90.482,...,81.260,104.101,82.563,64.994,83.853,87.333,67.862,NaN,NaN,NaN
2001,71.607,91.561,76.629,54.860,99.800,68.547,65.037,65.837,82.017,90.942,...,82.023,102.321,85.093,64.604,86.098,89.311,68.028,NaN,NaN,NaN
2002,72.261,92.016,76.699,56.253,99.689,68.584,64.310,68.003,80.964,91.530,...,81.274,102.020,85.010,63.845,83.723,89.362,67.944,NaN,NaN,NaN
2003,72.511,92.493,77.262,58.823,98.442,69.004,64.718,69.428,79.308,92.119,...,82.789,103.280,83.580,64.266,82.155,87.988,68.283,NaN,NaN,NaN
2004,73.119,92.891,78.413,61.776,100.379,70.342,66.795,73.651,77.546,92.130,...,85.049,103.473,84.641,66.519,81.268,89.284,69.752,NaN,NaN,NaN
2005,73.531,93.000,77.820,64.079,100.491,71.218,68.146,73.950,74.686,91.704,...,86.268,102.763,85.897,67.891,81.930,90.027,70.656,NaN,NaN,NaN
2006,74.495,93.801,78.257,65.874,100.309,72.310,69.455,74.374,72.506,92.599,...,88.215,102.183,85.325,69.222,84.058,89.399,71.809,NaN,NaN,NaN
2007,75.890,94.356,80.449,67.658,102.550,74.412,72.235,77.391,74.252,93.763,...,90.156,103.125,88.722,72.134,84.860,91.823,73.987,NaN,NaN,NaN
2008,80.736,95.811,84.087,70.976,105.504,80.175,79.351,81.261,76.977,95.555,...,91.981,103.561,92.503,79.605,96.812,95.037,80.178,82.793,85.849,84.097
2009,82.760,96.706,81.550,71.753,104.853,82.005,81.295,82.895,74.585,96.725,...,92.234,104.850,90.928,81.683,96.696,94.141,82.226,82.309,85.647,83.811
2010,83.276,97.287,85.870,74.179,105.299,83.124,83.193,84.692,83.275,97.167,...,92.836,103.193,92.223,83.622,97.581,94.785,83.404,85.395,87.941,86.335
2011,85.617,97.498,91.858,76.806,92.328,85.669,86.148,86.629,94.225,97.332,...,93.891,102.286,92.847,86.504,104.992,92.487,85.995,89.787,89.877,89.651
2012,87.323,99.128,96.682,79.955,92.971,87.629,88.285,90.791,101.097,98.450,...,95.510,102.246,93.850,88.653,111.339,93.395,87.906,93.186,92.983,92.842
2013,89.000,99.479,98.738,83.271,94.353,89.468,90.335,94.317,103.486,98.754,...,98.568,101.172,94.702,90.429,113.246,94.601,89.629,95.226,94.102,94.444
2014,91.763,98.748,99.441,86.206,96.134,92.112,92.995,97.092,101.943,97.713,...,99.128,100.919,96.155,93.054,112.663,96.430,92.326,96.183,95.818,95.678
2015,93.584,98.654,100.093,89.381,96.605,93.844,94.194,94.040,99.245,98.042,...,98.746,101.055,96.355,94.127,108.606,96.821,93.821,96.056,95.470,95.946
2016,95.209,98.908,98.791,92.134,98.043,95.734,96.319,93.388,96.343,98.375,...,99.098,100.588,97.241,96.244,104.432,97.644,95.661,96.184,95.655,96.297
2017,96.848,99.576,99.816,94.981,98.062,97.115,97.565,96.378,99.223,99.159,...,99.623,101.068,97.670,97.401,101.881,97.871,97.089,97.896,97.381,97.893
2018,98.358,100.915,99.324,97.664,99.222,98.512,98.861,98.706,98.882,100.428,...,99.761,100.131,98.893,98.778,100.741,98.971,98.541,98.986,99.148,99.179
2019,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000

>The returned datasets can be filtered by frequency of the timeseries and/or the start year. To demonstrate this, we filter the returned datasets based on frequency, filtering for datasets with 'annual' frequency. Note that the in_place argument is set to True, thus modifying the original timeseries_search() object.

In [10]:
data.filter_datasets('annual', inplace=True)

,resourceId,title,frequency,uom,datasource,footnote,startPeriod,endPeriod,variables
2,17091,Percent Change In Consumer Price Index (CPI) B...,Annual,Per Cent,SINGAPORE DEPARTMENT OF STATISTICS,"""The weighting pattern for the 2019-based CPI ...",1994,2019,"[{'variableCode': 'M213021.4.1.2', 'variableNa..."
3,17092,Consumer Price Index (CPI) By Household Income...,Annual,Index,SINGAPORE DEPARTMENT OF STATISTICS,"""The weighting pattern for the 2019-based CPI ...",1993,2019,"[{'variableCode': 'M213011.2.1.2', 'variableNa..."

In [14]:
data.resource_ids

[17091, 17092]